language: c
version: ~> 1.0

addons:
  apt:
    packages:
    - discount
    - make
    - libncurses-dev
    - libglib2.0-dev
    - libsdl2-dev
    - libsdl2-ttf-dev
    - zlib1g-dev

os:
  - linux

compiler:
  - clang
  - gcc

env:
  - CONFIGURATION="config=debug"
  - CONFIGURATION="config=release"
  - CONFIGURATION="config=debug SETGID=Y"
  - CONFIGURATION="config=release SETGID=Y"
  - CONFIGURATION="config=debug SDLPDCURSES=Y"
  - CONFIGURATION="config=release SDLPDCURSES=Y"

script:
  make $CONFIGURATION
